sudo: required
services:
  - docker

before_install:
  - docker build -t jordanm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jordanm/docker-react npm run test

delpoy:
  edge: true
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-479263233019"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"